config/routes.rb
Mongey::Application.routes.draw do
  get "login" =>  "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "user" => "users#index", :as => "user"
  get "user/settings" => "users#settings", :as => "user_settings"
  put "user/settings" => "users#save_settings", :as => "user_settings"

  resources :users, :only => [:create]

  resources :sessions

  resources :currencies
  resources :categories

  resources :events
  resources :payments
  resources :deposits
  resources :transfers

  resources :transactions

  resources :accounts
  resources :payees do
    collection do
      get 'autocomplete'
    end
  end
  resources :bankaccounts

  root :to => 'home#index'
end

app/models/currency.rb
class Currency
  include Mongoid::Document
  include Mongoid::Paranoia

  field :code, :type => String
  field :prefix, :type => String
  field :suffix, :type => String
  field :thousand_separator, :type => String
  field :decimal_point, :type => String

  has_many :accounts
  has_many :users

  validates_presence_of :code
  validates_uniqueness_of :code

  def format(amount)
    a = '%.2f' % amount
    "#{prefix}#{a}#{suffix}"    
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
  def format_currency(value, currency)
    return "0.00" if value.nil?
    return currency.format(value) unless currency.nil?
    '%.2f' % value
  end
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :prefix %><br />
    <%= f.text_field :prefix %>
  </div>
  <div class="field">
    <%= f.label :suffix %><br />
    <%= f.text_field :suffix %>
  </div>
  <div class="field">
    <%= f.label :thousand_separator %><br />
    <%= f.text_field :thousand_separator %>
  </div>
  <div class="field">
    <%= f.label :decimal_point %><br />
    <%= f.text_field :decimal_point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Prefix</th>
    <th>Suffix</th>
    <th>Thousand separator</th>
    <th>Decimal point</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.code %></td>
    <td><%= currency.prefix %></td>
    <td><%= currency.suffix %></td>
    <td><%= currency.thousand_separator %></td>
    <td><%= currency.decimal_point %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p>
  <b>Code:</b>
  <%= @currency.code %>
</p>

<p>
  <b>Prefix:</b>
  <%= @currency.prefix %>
</p>

<p>
  <b>Suffix:</b>
  <%= @currency.suffix %>
</p>

<p>
  <b>Thousand separator:</b>
  <%= @currency.thousand_separator %>
</p>

<p>
  <b>Decimal point:</b>
  <%= @currency.decimal_point %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>