config/routes.rb
Mongey::Application.routes.draw do
  get "login" =>  "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "user" => "users#index", :as => "user"
  get "user/settings" => "users#settings", :as => "user_settings"
  put "user/settings" => "users#save_settings", :as => "user_settings"

  resources :users, :only => [:create]

  resources :sessions

  resources :currencies
  resources :categories

  resources :events
  resources :payments
  resources :deposits
  resources :transfers

  resources :transactions

  resources :accounts
  resources :payees do
    collection do
      get 'autocomplete'
    end
  end
  resources :bankaccounts

  root :to => 'home#index'
end

app/models/payee.rb
class Payee < Account
  field :customer_number, :type => String
  field :notes, :type => String
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController

  def index
    @payees = Payee.all
  end

  def show
    @payee = Payee.find(params[:id])
  end

  def new
    @payee = Payee.new
  end

  def create
    @payee = Payee.new(params[:payee])

    if @payee.save
      redirect_to @payee, notice: 'Payee was successfully created.'
    else
      render action: "new"
    end
  end

  def autocomplete
    if params[:term]
      regex = /#{params[:term]}/i
      payees = Payee.where(name: regex)
    else
      payees = Payee.all
    end
    list = payees.map {|p| Hash[id: p.id, label: p.name, name: p.name]}
    render json: list
  end
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/views/payees/_form.html.erb
<%= form_for(@payee) do |f| %>
  <% if @payee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payee.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @payee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :customer_number %><br />
    <%= f.text_field :customer_number %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/payees/index.html.erb
<h1>Payees</h1>
<p><strong>Found <%= @payees.count %> payees.</strong><p>

<table>
  <% @payees.each do |payee| %>
  <tr>
    <td><%= payee.name %></td>
  </tr>
  <% end %>
</table>

app/views/payees/new.html.erb
<h1>New Payee</h1>

<%= render 'form' %>

app/views/payees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @payee.name %>
</p>

<p>
  <b>Customer Number:</b>
  <%= @payee.customer_number %>
</p>

<p>
  <b>Notes:</b>
  <%= @payee.notes %>
</p>


<%= link_to 'Edit', edit_payee_path(@payee) %> |
<%= link_to 'Back', payees_path %>

<table>
<% @payee.transactions.each do |t| %>
  <tr>
    <td><%= t.memo %></td>
    <td><%= t.credit %></td>
    <td><%= t.debit %></td>
    <td><%= t.transaction.memo %></td>
    <td><%= t.category.name %></td>
  </tr>
<% end %>
</table>