config/routes.rb
Mongey::Application.routes.draw do
  get "login" =>  "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "user" => "users#index", :as => "user"
  get "user/settings" => "users#settings", :as => "user_settings"
  put "user/settings" => "users#save_settings", :as => "user_settings"

  resources :users, :only => [:create]

  resources :sessions

  resources :currencies
  resources :categories

  resources :events
  resources :payments
  resources :deposits
  resources :transfers

  resources :transactions

  resources :accounts
  resources :payees do
    collection do
      get 'autocomplete'
    end
  end
  resources :bankaccounts

  root :to => 'home#index'
end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia

  field :name, :type => String
  field :opening_date, :type => Date
  field :opening_balance, :type => Money, :default => 0.ones
  field :balance, :type => Money, :default => 0.ones

  attr_accessor :initial_balance
  attr_reader :currency_id

  validates :name, :presence => true
  validates :opening_date, :presence => true
  validates :initial_balance, :presence => {:on => :create},
                              :numericality => {:on => :create}

  has_many :transactions
  belongs_to :user
  belongs_to :currency

  validates_associated :currency

  before_save :set_balance
  
  def process_transaction(transaction)
    balance = self.balance + transaction.credit - transaction.debit
    update_attributes(:balance => balance)
  end

private
  def set_balance
    if initial_balance.present?
      self.opening_balance = Money.new_from_ones(initial_balance.to_f)
      self.balance = Money.new_from_ones(initial_balance.to_f)
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = current_user.accounts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = current_user.accounts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  def new

  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def child_account_path(account)
    case account
      when Bankaccount then bankaccount_path(account)
      when Payee then payee_path(account)
      else account_path(account)
    end
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :opening_date %><br />
    <%= f.date_select :opening_date %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br />
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :credit_limit %><br />
    <%= f.text_field :credit_limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= link_to account.name, account %></td>
    <td class="cell-right"><%= format_currency(account.balance, account.currency) %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account_path(account), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>
<h2>Choose type:</h2>
<ul>
  <li><%= link_to "Bank account", new_bankaccount_path %></li>
  <li>Savings account</li>
  <li>Portfolio</li>
</ul>


<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>

<p>
  <b>Balance:</b>
  <%= format_currency(@account.balance, @account.currency) %>
</p>

<p>
  <b>Number:</b>
  <%= @account.number %>
</p>

<p>
  <b>Opening date:</b>
  <%= @account.opening_date %>
</p>

<p>
  <b>Interest rate:</b>
  <%= @account.interest_rate %>
</p>

<p>
  <b>Credit limit:</b>
  <%= @account.credit_limit %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

<h2>Recent transactions</h2>
<table>
  <tr>
    <td>Date</td>
    <td>Memo</td>
    <td>Amount</td>
    <td>Category</td>
  </tr>
<% @account.transactions.each do |t| %>
  <tr>
    <td><%= t.event.operation_date %></li>
    <td><%= t.memo %></td>
    <td><%= t.credit - t.debit %></td>
    <td><%= link_to t.category.name, t.category %></td>
  </tr>
<% end %>
</table>